CREATE TABLE IF NOT EXISTS SPENDING(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	SPENDING_ID INT NOT NULL,
	SUSPECT_ID INT NOT NULL,
	DATA_TRANS TEXT NOT NULL,
	VALOR REAL NOT NULL,
	ESTABELECIMENTO TEXT,
	NOME_FANTASIA TEXT,
	SECAO TEXT,
	NOME_UF TEXT,
	RESULTADO INTEGER,
	PROBABILIDADE REAL,
	SHAP TEXT,
	FOREIGN KEY(SUSPECT_ID) REFERENCES SUSPECT(ID))

-- # Populate Spending Table

INSERT INTO SPENDING (
	SPENDING_ID,
	SUSPECT_ID,
	DATA_TRANS,
	VALOR,
	ESTABELECIMENTO,
	NOME_FANTASIA,
	SECAO,
	NOME_UF,
	RESULTADO,
	PROBABILIDADE
)
SELECT
	C.id,
	S.ID,
	C.dataTransacao,
	C.valorTransacao,
	C.nome_estabelecimento,
	C.nomeFantasiaReceita,
	C.secao,
	C.nome_uf,
	R.result, 
	R.score
FROM CARTOES C
INNER JOIN RESULTS R ON R.id = C.id
INNER JOIN SUSPECT S ON S.NOME || S.CPF = C.nome_portador || C.codigoFormatado_portador
WHERE C.nome_portador || C.codigoFormatado_portador IN (SELECT NOME || CPF FROM SUSPECT)