CREATE TABLE IF NOT EXISTS SPENDING(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	DATA_TRANS TEXT NOT NULL,
	VALOR REAL NOT NULL,
	ESTABELECIMENTO TEXT,
	NOME_FANTASIA TEXT,
	SECAO TEXT,
	NOME_UF TEXT,
	RESULTADO INTEGER,
	PROBABILIDADE REAL,
	SHAP TEXT);
