CREATE TABLE IF NOT EXISTS SUSPECTS(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
NOME TEXT NOT NULL,
CPF TEXT NOT NULL,
PODER TEXT NOT NULL,
ORGAO_MAXIMO TEXT NOT NULL,
ORGAO_VINCULADO TEXT NOT NULL,
UNIDADE_GESTORA TEXT NOT NULL,
CARGO TEXT,
ESTADO_NASCIMENTO TEXT);

CREATE TABLE POLITIC_PARTY(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
NOME TEXT NOT NULL);

CREATE TABLE SUSPECT_POLITIC_PARTY(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
SUSPECT_ID INTEGER NOT NULL,
POLITIC_PARTY_ID INTEGER NOT NULL,
FOREIGN KEY(SUSPECT_ID) REFERENCES SUSPECTS(ID),
FOREIGN KEY(POLITIC_PARTY_ID) REFERENCES POLITIC_PARTY(ID));