CREATE TABLE IF NOT EXISTS SUSPECT(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
NOME TEXT NOT NULL,
CPF TEXT NOT NULL,
PODER TEXT NOT NULL,
ORGAO_MAXIMO TEXT NOT NULL,
ORGAO_VINCULADO TEXT NOT NULL,
UNIDADE_GESTORA TEXT NOT NULL,
CARGO TEXT,
ESTADO_NASCIMENTO TEXT,
IMAGEM TEXT DEFAULT NULL,
GASTOS_ANOMALOS INTEGER,
GASTOS_NORMAIS INTEGER,
TOTAL_GASTO REAL);

CREATE TABLE POLITIC_PARTY(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
NOME TEXT NOT NULL);

CREATE TABLE SUSPECT_POLITIC_PARTY(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
SUSPECT_ID INTEGER NOT NULL,
POLITIC_PARTY_ID INTEGER NOT NULL,
ATUAL INTEGER DEFAULT 0,
FOREIGN KEY(SUSPECT_ID) REFERENCES SUSPECT(ID),
FOREIGN KEY(POLITIC_PARTY_ID) REFERENCES POLITIC_PARTY(ID));

-- #### Add Suspect ####

-- INSERT INTO SUSPECT (NOME,
-- CPF,
-- PODER,
-- ORGAO_MAXIMO,
-- ORGAO_VINCULADO,
-- UNIDADE_GESTORA,
-- CARGO,
-- ESTADO_NASCIMENTO)
-- SELECT nome_portador, codigoFormatado_portador, descricaoPoder, nome_orgaoMaximo, nome_orgaoVinculado, nome_unidadeGestora, '67º Prefeito de Maceió', 'Maceió, AL, Brasil' 
-- FROM CARTOES WHERE nome_portador = 'JOSE WEYNE NUNES MARCELINO' LIMIT 1


--- #### Add TOTALs ####

-- UPDATE SUSPECT SET GASTOS_ANOMALOS = (
-- 	SELECT COUNT(*) FROM CARTOES
-- 		INNER JOIN RESULTS ON CARTOES.id = RESULTS.id
-- 		WHERE codigoFormatado_portador = (
-- 			SELECT CPF FROM SUSPECT WHERE ID = 10
-- 		)
-- 		AND result = -1
-- ) WHERE ID = 10;

-- UPDATE SUSPECT SET GASTOS_NORMAIS = (
-- 	SELECT COUNT(*) FROM CARTOES
-- 		INNER JOIN RESULTS ON CARTOES.id = RESULTS.id
-- 		WHERE codigoFormatado_portador = (
-- 			SELECT CPF FROM SUSPECT WHERE ID = 10
-- 		)
-- 		AND result = 1
-- ) WHERE ID = 10;



-- UPDATE SUSPECT SET TOTAL_GASTO = (
-- 	SELECT SUM(valorTransacao) FROM CARTOES WHERE codigoFormatado_portador = (
-- 		SELECT CPF FROM SUSPECT WHERE ID = 10
-- 	)
-- ) WHERE ID = 10;
